# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import Optional
from typing_extensions import Literal, TypedDict

from .._types import SequenceNotStr
from .dtmf_type import DtmfType
from .encrypted_media import EncryptedMedia
from .anchorsite_override import AnchorsiteOverride
from .connection_rtcp_settings_param import ConnectionRtcpSettingsParam
from .shared_params.connection_jitter_buffer import ConnectionJitterBuffer
from .shared_params.connection_noise_suppression_details import ConnectionNoiseSuppressionDetails

__all__ = ["UacConnectionUpdateParams", "ExternalUacSettings", "Inbound", "InternalUacSettings", "Outbound"]


class UacConnectionUpdateParams(TypedDict, total=False):
    active: bool
    """Defaults to true"""

    anchorsite_override: AnchorsiteOverride
    """
    `Latency` directs Telnyx to route media through the site with the lowest
    round-trip time to the user's connection. Telnyx calculates this time using ICMP
    ping messages. This can be disabled by specifying a site to handle all media.
    """

    android_push_credential_id: Optional[str]
    """The uuid of the push credential for Android"""

    call_cost_in_webhooks: bool
    """Specifies if call cost webhooks should be sent for this connection."""

    connection_name: str
    """A user-assigned name to help manage the connection."""

    default_on_hold_comfort_noise_enabled: bool
    """When enabled, Telnyx will generate comfort noise when you place the call on
    hold.

    If disabled, you will need to generate comfort noise or on hold music to avoid
    RTP timeout.
    """

    dtmf_type: DtmfType
    """Sets the type of DTMF digits sent from Telnyx to this Connection.

    Note that DTMF digits sent to Telnyx will be accepted in all formats.
    """

    encode_contact_header_enabled: bool
    """
    Encode the SIP contact header sent by Telnyx to avoid issues for NAT or ALG
    scenarios.
    """

    encrypted_media: Optional[EncryptedMedia]
    """Enable use of SRTP for encryption.

    Cannot be set if the transport_portocol is TLS.
    """

    external_uac_settings: ExternalUacSettings
    """
    External SIP peer settings used by Telnyx when registering to your PBX and
    routing outbound calls.
    """

    inbound: Inbound
    """Inbound settings that can be supplied when creating or updating a UAC
    connection.

    The SIP subdomain fields returned in UAC connection responses are generated by
    Telnyx and are not accepted as request parameters.
    """

    internal_uac_settings: InternalUacSettings
    """Internal Telnyx-side settings for a UAC connection."""

    ios_push_credential_id: Optional[str]
    """The uuid of the push credential for Ios"""

    jitter_buffer: ConnectionJitterBuffer
    """Configuration options for Jitter Buffer.

    Enables Jitter Buffer for RTP streams of SIP Trunking calls. The feature is off
    unless enabled. You may define min and max values in msec for customized
    buffering behaviors. Larger values add latency but tolerate more jitter, while
    smaller values reduce latency but are more sensitive to jitter and reordering.
    """

    noise_suppression: Literal["inbound", "outbound", "both", "disabled"]
    """Controls when noise suppression is applied to calls.

    When set to 'inbound', noise suppression is applied to incoming audio. When set
    to 'outbound', it's applied to outgoing audio. When set to 'both', it's applied
    in both directions. When set to 'disabled', noise suppression is turned off.
    """

    noise_suppression_details: ConnectionNoiseSuppressionDetails
    """Configuration options for noise suppression.

    These settings are stored regardless of the noise_suppression value, but only
    take effect when noise_suppression is not 'disabled'. If you disable noise
    suppression and later re-enable it, the previously configured settings will be
    used.
    """

    onnet_t38_passthrough_enabled: bool
    """
    Enable on-net T38 if you prefer the sender and receiver negotiating T38 directly
    if both are on the Telnyx network. If this is disabled, Telnyx will be able to
    use T38 on just one leg of the call depending on each leg's settings.
    """

    outbound: Outbound

    password: str
    """The password to be used as part of the credentials.

    Must be 8 to 128 characters long.
    """

    rtcp_settings: ConnectionRtcpSettingsParam

    sip_uri_calling_preference: Literal["disabled", "unrestricted", "internal"]
    """This feature enables inbound SIP URI calls to your Credential Auth Connection.

    If enabled for all (unrestricted) then anyone who calls the SIP URI
    <your-username>@telnyx.com will be connected to your Connection. You can also
    choose to allow only calls that are originated on any Connections under your
    account (internal).
    """

    tags: SequenceNotStr[str]
    """Tags associated with the connection."""

    user_name: str
    """The user name to be used as part of the credentials.

    Must be 4-32 characters long and alphanumeric values only (no spaces or special
    characters).
    """

    webhook_api_version: Literal["1", "2"]
    """Determines which webhook format will be used, Telnyx API v1 or v2."""

    webhook_event_failover_url: Optional[str]
    """
    The failover URL where webhooks related to this connection will be sent if
    sending to the primary URL fails. Must include a scheme, such as 'https'.
    """

    webhook_event_url: str
    """The URL where webhooks related to this connection will be sent.

    Must include a scheme, such as 'https'.
    """

    webhook_timeout_secs: Optional[int]
    """Specifies how many seconds to wait before timing out a webhook."""


class ExternalUacSettings(TypedDict, total=False):
    """
    External SIP peer settings used by Telnyx when registering to your PBX and routing outbound calls.
    """

    auth_username: Optional[str]
    """The authentication username used in SIP digest authentication.

    If not set, the Username value will be used.
    """

    expiration_sec: Optional[int]
    """
    The registration interval, in seconds, indicating how often the system refreshes
    the SIP registration with the external SIP peer.
    """

    from_user: Optional[str]
    """The user portion of the SIP From header used in outbound requests.

    This controls the caller identity presented to the external SIP peer.
    """

    outbound_proxy: Optional[str]
    """
    An optional SIP proxy used to route outbound requests before reaching the
    external SIP peer.
    """

    password: str
    """The SIP password used for digest authentication with the external SIP peer."""

    proxy: str
    """
    The SIP proxy address of the external SIP peer used for registrations and
    outbound call routing.
    """

    transport: Optional[Literal["UDP", "TLS", "TCP"]]
    """
    The transport protocol used for SIP signaling when communicating with the
    external SIP peer. One of UDP, TLS, or TCP.
    """

    username: str
    """
    The SIP username used to authenticate with the external SIP peer for
    registrations and outbound calls. Must start with a letter or number and contain
    only letters, numbers, hyphens, and underscores.
    """


class Inbound(TypedDict, total=False):
    """Inbound settings that can be supplied when creating or updating a UAC connection.

    The SIP subdomain fields returned in UAC connection responses are generated by Telnyx and are not accepted as request parameters.
    """

    ani_number_format: Literal["+E.164", "E.164", "+E.164-national", "E.164-national"]
    """
    This setting allows you to set the format with which the caller's number (ANI)
    is sent for inbound phone calls.
    """

    channel_limit: int
    """
    When set, this will limit the total number of inbound calls to phone numbers
    associated with this connection.
    """

    codecs: SequenceNotStr[str]
    """
    Defines the list of codecs that Telnyx will send for inbound calls to a specific
    number on your portal account, in priority order. This only works when the
    Connection the number is assigned to uses Media Handling mode: default. OPUS and
    H.264 codecs are available only when using TCP or TLS transport for SIP.
    """

    default_routing_method: Literal["sequential", "round-robin"]
    """
    Default routing method to be used when a number is associated with the
    connection. Must be one of the routing method types or left blank, other values
    are not allowed.
    """

    dnis_number_format: Literal["+e164", "e164", "national", "sip_username"]

    generate_ringback_tone: bool
    """Generate ringback tone through 183 session progress message with early media."""

    isup_headers_enabled: bool
    """When set, inbound phone calls will receive ISUP parameters via SIP headers.

    (Only when available and only when using TCP or TLS transport.)
    """

    prack_enabled: bool
    """Enable PRACK messages as defined in RFC3262."""

    shaken_stir_enabled: bool
    """
    When enabled the SIP Connection will receive the Identity header with
    Shaken/Stir data in the SIP INVITE message of inbound calls, even when using UDP
    transport.
    """

    simultaneous_ringing: Literal["disabled", "enabled"]
    """When enabled, allows multiple devices to ring simultaneously on incoming calls."""

    sip_compact_headers_enabled: bool
    """Defaults to true."""

    timeout_1xx_secs: int
    """Time(sec) before aborting if connection is not made."""

    timeout_2xx_secs: int
    """Time(sec) before aborting if call is unanswered (min: 1, max: 600)."""


class InternalUacSettings(TypedDict, total=False):
    """Internal Telnyx-side settings for a UAC connection."""

    destination_uri: str
    """
    The SIP URI that Telnyx will call when handling an inbound request from the
    external peer. Do not include a `sip:` prefix. The value must be in the format
    `userinfo@<subdomain.>sip.telnyx.com` or
    `userinfo@<subdomain.>sipdev.telnyx.com`; the userinfo portion may contain only
    letters, digits, hyphens, and underscores.
    """


class Outbound(TypedDict, total=False):
    ani_override: str
    """
    Set a phone number as the ani_override value to override caller id number on
    outbound calls.
    """

    ani_override_type: Literal["always", "normal", "emergency"]
    """Specifies when we apply your ani_override setting.

    Only applies when ani_override is not blank.
    """

    call_parking_enabled: Optional[bool]
    """
    Forces all SIP calls originated on this connection to be "parked" instead of
    "bridged" to the destination specified on the URI. Parked calls will return
    ringback to the caller and will await for a Call Control command to define which
    action will be taken next.
    """

    channel_limit: int
    """
    When set, this will limit the total number of outbound calls to phone numbers
    associated with this connection.
    """

    generate_ringback_tone: bool
    """Generate ringback tone through 183 session progress message with early media."""

    instant_ringback_enabled: bool
    """
    When set, ringback will not wait for indication before sending ringback tone to
    calling party.
    """

    localization: str
    """
    A 2-character country code specifying the country whose national dialing rules
    should be used. For example, if set to `US` then any US number can be dialed
    without preprending +1 to the number. When left blank, Telnyx will try US and GB
    dialing rules, in that order, by default.
    """

    outbound_voice_profile_id: str
    """Identifies the associated outbound voice profile."""

    t38_reinvite_source: Literal["telnyx", "customer", "disabled", "passthru", "caller-passthru", "callee-passthru"]
    """This setting only affects connections with Fax-type Outbound Voice Profiles.

    The setting dictates whether or not Telnyx sends a t.38 reinvite.<br/><br/> By
    default, Telnyx will send the re-invite. If set to `customer`, the caller is
    expected to send the t.38 reinvite.
    """
