name: Auto-merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: |
          # Wait for all checks to complete
          gh pr checkout "$PR_URL"
          while true; do
            checks_status=$(gh pr checks "$PR_URL" --json conclusion -q '.[].conclusion' | uniq)
            if [[ "$checks_status" == "success" ]]; then
              gh pr merge --auto --merge "$PR_URL"
              break
            elif [[ "$checks_status" == *"failure"* ]] || [[ "$checks_status" == *"cancelled"* ]]; then
              echo "Checks failed or were cancelled. Not merging."
              exit 1
            fi
            echo "Waiting for checks to complete..."
            sleep 30
          done
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}