name: Python
on:
  [push]
jobs:
  test:
    env:
      TELNYX_MOCK_VERSION: 0.8.10
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9, pypy-2.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: gabrielfalcao/pyenv-action@v7
      - uses: dschep/install-pipenv-action@v1
      - name: setup-telnyx-mock
        run: source ./.github/scripts/before_install.sh
      - name: init
        run: make init
      - name: lint
        run: source ./.github/scripts/lint.sh
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
      - name: ci
        run: make ci
      - name: coveralls
        run: make coveralls

